
% MATLAB Code from Sensor Array Analyzer App

% Generated by MATLAB 9.13 and Phased Array System Toolbox 4.8

% Generated on 31-Jan-2023 16:26:19

% Create a Uniform Linear Array Object
Array = phased.ULA('NumElements',2,...
    'ArrayAxis','y');
% The multiplication factor for lambda units to meter conversion
Array.ElementSpacing = 0.5*1.11940298507463;
Array.Taper = ones(1,2).';

% Create an isotropic antenna element
Elem = phased.IsotropicAntennaElement;
Elem.FrequencyRange = [0 268000000];
Array.Element = Elem;

% Assign Frequencies and Propagation Speed
Frequency = 268000000;
PropagationSpeed = 300000000;

% Assign Steering Angles
SteeringAngles = [60;0];
% Assign Phase shift quantization bits
PhaseShiftBits = 3;

% Create Figure

% Plot Array Geometry
figure;
viewArray(Array,'ShowNormal',false,...
    'ShowTaper',false,'ShowIndex','None',...
    'ShowLocalCoordinates',true,'ShowAnnotation',false,...
    'Orientation',[0;0;0]);

% Find the weights
w = zeros(getNumElements(Array), length(Frequency));
for idx = 1:length(Frequency)
    SteerVector = phased.SteeringVector('SensorArray', Array,...
        'PropagationSpeed', PropagationSpeed, ...
        'NumPhaseShifterBits', PhaseShiftBits(idx));
    w(:, idx) = step(SteerVector, Frequency(idx), SteeringAngles(:, idx));
end
% w = [1;-1];

% Plot 2d azimuth graph
format = 'polar';
cutAngle = 0;
plotType = 'Directivity';
plotStyle = 'Overlay';
figure;
pattern(Array, Frequency, -180:180, cutAngle, 'PropagationSpeed', PropagationSpeed,...
    'CoordinateSystem', format ,'weights', w, ...
    'Type', plotType, 'PlotStyle', plotStyle);

